server:
  port: 7095


spring:  config:    import:    - configserver:http://localhost:8888
  cloud:    bus:      enabled: true
  kafka:    bootstrap-servers:    - ${KAFKA_ADDR:http://localhost:9092}

 
   


management:  endpoints:    web:      exposure:        include:        - "*"

 