
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"  
  
spring:  config:    import: configserver:http://localhost:8888
    
  application:    name: customer-service-two  


