server:
  port: 5054
  
spring:  application:    name: customer-service  
    
    
eureka:  client:    service-url:      defaultZone: http://eureka-peer1:8770/eureka  
      

management:  endpoints:    web:      exposure:        include:        - "*"      