server:
  port: 8080
  

spring:  application:    name: cloud-gateway  
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 3859625a090362040b64
            client-secret: 2fff1aeda9834e99a46ddb4580cf415c29309aee
            scope:
            - "['read','write']"
 
eureka:  client:    fetch-registry: true
    register-with-eureka: true
    service-url:      defaultZone: http://localhost:8761/eureka  
      

management:  endpoints:    web:      exposure:        include:        - "*"      