spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: srivatsan
    driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:    hibernate:      ddl-auto: update
    show-sql: true  application:    name: restaurant-info-service    
server:  port: 7075    

eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka  
  
com:
  example:
    demo:
      errorcode:
        one: Element Not Present in Table  
  