spring:
  application:
    name: order-delivery-service
  config:
    import: configserver:http://localhost:8888
    

server:  port: 6060
  
logging:  file:    name: e:\\logs\\oct2021.log
    
          